name: Release Obsidian Plugin

on:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "20.x"

      # Debug environment
      - name: Debug Environment
        run: |
          echo "=== Node/NPM Versions ==="
          node --version
          npm --version
          echo "=== TypeScript Version ==="
          npx tsc --version
          echo "=== Package.json build script ==="
          cat package.json | grep -A 1 -B 1 '"build"'
          echo "=== TSConfig ==="
          cat tsconfig.json
          echo "=== Installed packages versions ==="
          npm list typescript obsidian obsidian-typings --depth=0

      # Build the plugin
      - name: Build
        id: build
        run: |
          npm install
          echo "=== Running build command ==="
          npm run build --if-present

      # Create the release on GitHub
      - name: Create Release
        id: create_release
        uses: ncipollo/release-action@v1.13.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VERSION: ${{ github.ref }}
        with:
          allowUpdates: true
          generateReleaseNotes: true
          artifactErrorsFailBuild: false
          makeLatest: true
          artifacts: "manifest.json,main.js,styles.css"
          bodyFile: ".github/workflows/release-body.md"
